#!/bin/sh
#
# <ServiceName>       Bring up/down <Service name>
#
# chkconfig: 2345 55 25
# description: Validate eTransport or eFactura xml files
#
### BEGIN INIT INFO
# Provides: validation eTransport or eFactura
# Should-Start: octsoftschematron
# Short-Description: validation eTransport or eFactura
# Description: validation eTransport or eFactura
### END INIT INFO
SERVICE_NAME=octschematron
PATH_TO_JAR=/opt/octsoftschematron/
JAR_NAME=octschematron.jar
PID_PATH_NAME=/opt/octsoftschematron/$SERVICE_NAME-pid
#Changing to jar directory to allow use of application.properties file in same location
cd $PATH_TO_JAR
case $1 in
    start)
        echo "Starting $SERVICE_NAME ..."
        if [ ! -f $PID_PATH_NAME/$JAR_NAME ]; then
            nohup java -jar $JAR_NAME 2>> /dev/null  >> /dev/null &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is already running ..."
        fi
    ;;
    stop)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stoping ..."
            kill -9 $PID;
            echo "$SERVICE_NAME stopped ..."
            rm -f $PID_PATH_NAME
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
    restart)
        if [ -f $PID_PATH_NAME ]; then
            PID=$(cat $PID_PATH_NAME);
            echo "$SERVICE_NAME stopping ...";
            kill -9 $PID;
            echo "$SERVICE_NAME stopped ...";
            rm -f $PID_PATH_NAME
            echo "$SERVICE_NAME starting ..."
            nohup java -jar $JAR_NAME 2>> /dev/null  >> /dev/null &
                        echo $! > $PID_PATH_NAME
            echo "$SERVICE_NAME started ..."
        else
            echo "$SERVICE_NAME is not running ..."
        fi
    ;;
	status)
        if [ -f $PID_PATH_NAME ]; then
           echo "$SERVICE_NAME started ..."
        else
           echo "$SERVICE_NAME is not running ..."
        fi
    ;;
esac